# Generated by Django 2.0 on 2019-12-01 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_date', models.DateField()),
                ('close_price', models.FloatField()),
            ],
            options={
                'db_table': 'stocks_sh_detail',
            },
        ),
        migrations.CreateModel(
            name='SHHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=20)),
                ('stock_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'stocks_sh_header',
            },
        ),
        migrations.AddField(
            model_name='shdetail',
            name='stock_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cn_a_stocks.SHHeader'),
        ),
    ]
