# Generated by Django 2.0 on 2019-12-02 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AStocksCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'stocks_a_category',
            },
        ),
        migrations.CreateModel(
            name='AStocksDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_date', models.DateField()),
                ('close_price', models.FloatField()),
            ],
            options={
                'db_table': 'stocks_a_detail',
            },
        ),
        migrations.CreateModel(
            name='AStocksHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=20)),
                ('stock_code', models.CharField(max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cn_a_stocks.AStocksCategory')),
            ],
            options={
                'db_table': 'stocks_a_header',
            },
        ),
        migrations.AddField(
            model_name='astocksdetail',
            name='stock_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cn_a_stocks.AStocksHeader'),
        ),
    ]
