# Generated by Django 2.0 on 2019-12-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn_a_stocks', '0003_auto_20191203_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='astocksheader',
            name='area',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
