# Generated by Django 2.0 on 2019-12-03 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn_a_stocks', '0005_auto_20191203_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='astocksheader',
            name='isdelisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='ipodate',
            field=models.DateField(default=datetime.datetime(2019, 12, 3, 14, 36, 29, 730288)),
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='outdate',
            field=models.DateField(default=datetime.datetime(2019, 12, 3, 14, 36, 29, 730288)),
        ),
    ]
