# Generated by Django 2.0 on 2019-12-09 14:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cn_a_stocks', '0010_auto_20191208_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='AStocksDailyClsePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_date', models.DateField(null=True)),
                ('closing_price', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'stocks_a_closing_price',
            },
        ),
        migrations.RemoveField(
            model_name='astocksdetail',
            name='close_price',
        ),
        migrations.RemoveField(
            model_name='astocksdetail',
            name='exchange_date',
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='ipodate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 9, 22, 46, 52, 236121), null=True),
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='outdate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 9, 22, 46, 52, 236121), null=True),
        ),
        migrations.AddField(
            model_name='astocksdailyclseprice',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cn_a_stocks.AStocksHeader'),
        ),
    ]
