# Generated by Django 2.0 on 2019-12-10 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn_a_stocks', '0014_auto_20191210_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astocksdetail',
            name='stock_name',
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='ipodate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 10, 12, 4, 14, 897838), null=True),
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='outdate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 10, 12, 4, 14, 897838), null=True),
        ),
        migrations.DeleteModel(
            name='AStocksDetail',
        ),
    ]
