# Generated by Django 2.0 on 2019-12-10 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn_a_stocks', '0016_auto_20191210_1204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AStocksDailyClsePrice',
            new_name='AStocksClsePrice',
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='ipodate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 10, 12, 7, 33, 155838), null=True),
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='outdate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 10, 12, 7, 33, 155838), null=True),
        ),
    ]
