# Generated by Django 2.0 on 2019-12-11 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn_a_stocks', '0018_auto_20191211_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astocksheader',
            name='area',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='ipodate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 11, 14, 33, 14, 99050), null=True),
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='outdate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 11, 14, 33, 14, 99050), null=True),
        ),
    ]
