# Generated by Django 2.0 on 2019-12-12 03:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cn_a_stocks', '0019_auto_20191211_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='AStocksProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(null=True)),
                ('stat_date', models.DateField(null=True)),
                ('roe_avg', models.FloatField()),
                ('np_margin', models.FloatField()),
                ('gp_margin', models.FloatField()),
                ('net_profit', models.FloatField()),
                ('epsttm', models.FloatField()),
                ('mb_revenue', models.FloatField()),
                ('total_share', models.FloatField()),
                ('liqa_share', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='ipodate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 12, 11, 15, 55, 426626), null=True),
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='outdate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 12, 11, 15, 55, 426626), null=True),
        ),
        migrations.AddField(
            model_name='astocksprofit',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cn_a_stocks.AStocksHeader'),
        ),
    ]
