# Generated by Django 2.0 on 2019-12-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cn_a_stocks', '0019_auto_20191211_1433'),
        ('cn_a_stocks', '0018_auto_20191211_2201'),
    ]

    operations = [
    ]
