# Generated by Django 2.0 on 2019-12-12 03:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cn_a_stocks', '0021_auto_20191212_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='AStocksOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(null=True)),
                ('stat_date', models.DateField(null=True)),
                ('nr_turn_ratio', models.FloatField()),
                ('nr_turn_days', models.FloatField()),
                ('inv_turn_ratio', models.FloatField()),
                ('inv_turn_days', models.FloatField()),
                ('ca_turn_ratio', models.FloatField()),
                ('asset_turn_ratio', models.FloatField()),
            ],
            options={
                'db_table': 'stocks_a_operation',
            },
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='ipodate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 12, 11, 44, 2, 412780), null=True),
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='outdate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 12, 11, 44, 2, 412780), null=True),
        ),
        migrations.AddField(
            model_name='astocksoperation',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cn_a_stocks.AStocksHeader'),
        ),
    ]
