# Generated by Django 2.0 on 2019-12-12 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn_a_stocks', '0022_auto_20191212_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='astocksoperation',
            name='is_year_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='astocksprofit',
            name='is_year_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='ipodate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 12, 12, 58, 35, 762838), null=True),
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='outdate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 12, 12, 58, 35, 762838), null=True),
        ),
    ]
