# Generated by Django 2.0 on 2019-12-12 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn_a_stocks', '0024_auto_20191212_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='astocksgrowth',
            old_name='yoyequity',
            new_name='yoy_equity',
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='ipodate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 12, 15, 4, 57, 956223), null=True),
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='outdate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 12, 15, 4, 57, 956223), null=True),
        ),
    ]
