# Generated by Django 2.0 on 2019-12-12 07:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cn_a_stocks', '0025_auto_20191212_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='AStocksBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(null=True)),
                ('stat_date', models.DateField(null=True)),
                ('current_ratio', models.FloatField()),
                ('quick_ratio', models.FloatField()),
                ('cash_ratio', models.FloatField()),
                ('yoy_liability', models.FloatField()),
                ('liability_to_asset', models.FloatField()),
                ('asset_to_equity', models.FloatField()),
            ],
            options={
                'db_table': 'stocks_a_balance',
            },
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='ipodate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 12, 15, 12, 2, 210926), null=True),
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='outdate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 12, 15, 12, 2, 210926), null=True),
        ),
        migrations.AddField(
            model_name='astocksbalance',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cn_a_stocks.AStocksHeader'),
        ),
    ]
