# Generated by Django 2.0 on 2019-12-12 07:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cn_a_stocks', '0026_auto_20191212_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='AStocksCashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(null=True)),
                ('stat_date', models.DateField(null=True)),
                ('cat_to_asset', models.FloatField()),
                ('nca_to_asset', models.FloatField()),
                ('tangible_asset_to_asset', models.FloatField()),
                ('ebit_to_interest', models.FloatField()),
                ('cfo_to_or', models.FloatField()),
                ('cfo_to_np', models.FloatField()),
                ('cfo_to_gr', models.FloatField()),
            ],
            options={
                'db_table': 'stocks_a_cashflow',
            },
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='ipodate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 12, 15, 24, 41, 195046), null=True),
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='outdate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 12, 15, 24, 41, 195046), null=True),
        ),
        migrations.AddField(
            model_name='astockscashflow',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cn_a_stocks.AStocksHeader'),
        ),
    ]
