# Generated by Django 2.0 on 2019-12-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cn_a_stocks', '0027_auto_20191212_1524'),
        ('cn_a_stocks', '0020_merge_20191211_2203'),
    ]

    operations = [
    ]
