# Generated by Django 2.0 on 2019-12-16 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn_a_stocks', '0028_merge_20191212_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='astocksprofit',
            options={'ordering': ('-stat_date',)},
        ),
        migrations.AlterField(
            model_name='astocksclseprice',
            name='exchange_date',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='ipodate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 16, 10, 1, 3, 809242), null=True),
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='outdate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 16, 10, 1, 3, 809242), null=True),
        ),
    ]
