# Generated by Django 2.0 on 2019-12-16 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn_a_stocks', '0031_auto_20191216_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='astocksearnrate',
            name='create_date',
            field=models.DateField(auto_now_add=True, default='2019-12-16'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='astocksearnrate',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='ipodate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 16, 16, 11, 0, 199010), null=True),
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='outdate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 16, 16, 11, 0, 199010), null=True),
        ),
    ]
