# Generated by Django 2.0 on 2019-12-16 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn_a_stocks', '0034_auto_20191216_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='astocksearnrate',
            name='five_year',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='astocksearnrate',
            name='ten_year',
            field=models.TextField(default='2019-12-16'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='ipodate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 16, 22, 33, 6, 627081), null=True),
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='outdate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 16, 22, 33, 6, 627081), null=True),
        ),
    ]
