# Generated by Django 2.0 on 2019-12-19 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cn_a_stocks', '0038_auto_20191217_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='astockscategory',
            options={'ordering': ('category_name',), 'verbose_name': '板块', 'verbose_name_plural': '板块'},
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='ipodate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 19, 9, 55, 3, 345286), null=True),
        ),
        migrations.AlterField(
            model_name='astocksheader',
            name='outdate',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 19, 9, 55, 3, 345286), null=True),
        ),
    ]
